### PR TITLE
Code restructure/_fetch_favourite_episdodes addition

### PR DESCRIPTION
**Pull request by SumnerH**
So the diffs to default.py and service.py are pretty straightforward I think (as well as the addition to English.po, though it could actually use US/UK versioning).

It's the library.py restructuring that's bigger.  I put in a fair number of comments, but it's probably easier to read the full file than the diff.

Question:
In _get_data if you have a cached value of "" then you return None.  But if you check first and it's "LOADING" and then it comes back as "", then you return the empty string.  Is this intentional?  I've preserved that behavior, but you might want to always return None in this case (I'm not sure).

Overview:

1. Hoisted out the redundant logic of "Check whether we're caching/set property to LOADING/run query/set properties" into a _fetch_items method that everyone calls (passing in a callback to run the query at the correct time).
2. Pulled out the property lists and sort/filter dicts that were repeated in many places into variables that are reused instead
3. Instead of manually piecing together strings for the JSON request, there's now a json_query method that builds them from a set of parameters that are passed in; this avoids repeating some of the boilerplate over and over and should be more robust against problems.
4. The _fetch_recent_* methods are almost exactly the same as _fetch_random_* except for the sort order; they now just become a thin wrapper around each other.
5. Reimplemented everything else using (2) and (3); almost all of them are now tiny 4-line methods, except for _fetch_recommended_episodes which remains a little more complex by nature.
6. Implemented a new _fetch_favourite_episodes which returns the first unwatched episode from every show that's in your favourites; it's similarly complex to _fetch_recommended episodes.

Locally, I've added support for this in the TitanMediaBrowser skin (if you accept these changes I'll be submitting a patch to them next) and tested each of the above; they seem to work.

Let me know if you have any questions.

Thanks for your time and all your work,

Sumner

### CODE REVIEW

**Comment by BigNoid** [comment]
Nice work! 
One small thing, currently you do not check if the user has favorites. It will throw an ```typeerror: 'nonetype' object is not iterable``` in that case. Please fix that and I'll merge it in.

**Comment by SumnerH** [comment]
I just pushed up a fix for that--it looks like it's showing up here fine so I don't need to send a new pull request, right?

**Comment by BigNoid** [comment]
The PR automatically gets updated by pushing to your branch.
Thx!

**Comment by SumnerH** [comment]
Awesome.  Does this get released immediately, or is there some delay?  I want to contact some of the skin maintainers (especially Titan, since I've already done that work) with patches, but only after the new function is publicly available.

Thanks a ton for your time and all your contributions to kodi/xbmc!

**Comment by BigNoid** [comment]
I'll have to update it for the official repo. That can take a few days. I'll submit a PR today.

**Pull request merged**
