### PR TITLE
Skip shows if they don't have any episodes. May happen due to them be…

### PR DESCRIPTION
**Pull request by Razzeee**
…ing watched or only specials.

I can provide a database where this case happens if needed.

### CODE REVIEW

**Comment by Razzeee** [comment]
There may actually be a better solution. This is filtering quiet late in the chain and may lead to the limit you set in settings not being filled completely. In my case that mean I want 20 items for recommendedepisodes and I only get 19.

**Comment by BigNoid** [comment]
I'd like to take a look to see what happens, so if you could send me that database i'd appreciate it.

**Comment by Razzeee** [comment]
Uploading to slack right now.

**Comment by Razzeee** [comment]
Should be fixed by https://github.com/BigNoid/service.library.data.provider/commit/ed4192a90f6e73c72263492c285d59f525464ceb

**Pull request closed without merging**
